### ISSUE TITLE
/etc/localtime: invalid timezone file: no timezone found in OlsonData

### ISSUE THREAD

**Issue by jtdaugherty** [ygale/timezone-olson#10]
This library is having trouble parsing some timezone files from ArchLinux. I've attached an example. More details can be found at https://github.com/matterhorn-chat/matterhorn/issues/542. I'm not sure if this is a duplicate of #7, though.

[Sao_Paulo.zip](https://github.com/ygale/timezone-olson/files/4106191/Sao_Paulo.zip)

**Comment by jtdaugherty** [comment]
Greetings! Is there any way this can be fixed? This issue is still impacting some users.

**Comment by ygale** [comment]
Sao_Paulo does seem to parse now, but I don't know if the parsing is correct. Can you confirm whether this is in fact a duplicate of #7? If not, please supply more detail about what is going wrong. Thanks!

**Comment by jtdaugherty** [comment]
I tried version `0.2` of this library with the zip file attached above (after unzipping it). The result of calling `getTimeZoneSeriesFromOlsonFile` was a `TimeZoneSeries` value that `show`s as `-03`, which according to my research would seem to be the correct GMT offset for Sao Paolo. So from that I conclude that `0.2` fixes this issue and I can upgrade to `0.2` in the `matterhorn` project and notify our users. Thank you very much!
