### ISSUE TITLE
Please update Hackage

### ISSUE THREAD

**Issue by neilmayhew** [ygale/timezone-olson#9]
Various zone files (eg `Etc/UTC`) aren't handled on my system because they're using RFC 8536 and need 4ff152bd. Would you be able to upload a new version to Hackage, please?

**Comment by neilmayhew** [comment]
Any chance of some progress on this?

Also, tags to match Hackage releases would be nice.

Thanks.

**Comment by ygale** [comment]
Done, released as 0.2.0 on hackage, and tagged. Sorry for the delay.

**Comment by neilmayhew** [comment]
Thanks! Much appreciated.

**Comment by neilmayhew** [comment]
You may need to `git push --tags` since `0.2.0` isn't showing up on GitHub.

**Comment by ygale** [comment]
Done.
